spring:

  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: root
    password: daviAleixo1811@100
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: api

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true